### ISSUE TITLE
用info() 以上的log级别打印log ，删除所有system.out 

### ISSUE THREAD

**Issue by taotao0204** [starrykai/bugstorefront#1]
1）因为 部署后的项目，system.out 的内容 不能保存在 log 日志里，如果出问题无法跟踪
2）因为 hybris 已经有很多debug 级别底层的log，为了看log和读写日志的效率 ，通常我们在开发中的所有log 都定义为 info 以上，部署后就只开info 以上的log

**Comment by starrykai** [comment]
谢谢提醒，我查到了hybris使用log4j来管理日志。
