### ISSUE TITLE
灵活运用Converter 和 Populator

### ISSUE THREAD

**Issue by taotao0204** [starrykai/bugstorefront#2]
Converter/Populator 是代码灵活的数据转换框架设计，通过我们用spring 依赖注入的特性，把数据转换逻辑与业务逻辑分开，有效的降低耦合度，提高代码的复用性，以及扩展性。

参考：hybris/bin/ext-commerce/commercefacades/commercefacades-spring.xml 134 行 关于 productData 的转换。

例子：

bugstorefront/BugStoreFront/src/com/beforeship/bugstorefront/facades/impl/DefaultBugFacade.java
------------------------------------------------------------------------------------------
----------------------------------
	<bean id="defaultBugFacade"
	class="bugstorefront.BugStoreFront.src.com.beforeship.bugstorefront.facades.impl.DefaultBugFacade.java">
		<property name="xxxService" ref="xxService" />
		<property name="xxxService" ref="xxService" />	
		**<property name="bugConverter" ref="bugConverter" />**
	</bean>

	<bean id="bugConverter" parent="defaultBugConverter">
		<property name="populators">
			<list merge="true">
				**<ref bean="bugPopulator" />**
			</list>
		</property>
	</bean>
--------------------------------------------------------------------

**Comment by starrykai** [comment]
👍
